import * as d3 from 'd3-force';
import type { CanvasShape, CanvasArrow } from '../store/canvasStore';

export interface FileContent {
  id: string;
  name: string;    // e.g. "src/utils/helpers.ts"
  content: string;
}

// Regex-based import extractor.
const IMPORT_REGEX = /(?:import\s+.*?\s+from\s+['"]([^'"]+)['"]|require\s*\(\s*['"]([^'"]+)['"]\s*\))/g;

function resolvePath(baseDir: string, relativePath: string): string {
  if (!relativePath.startsWith('.')) return relativePath; // External or alias

  const baseParts = baseDir ? baseDir.split('/').filter(Boolean) : [];
  const relParts = relativePath.split('/');

  for (const part of relParts) {
    if (part === '.') continue;
    if (part === '..') {
      if (baseParts.length > 0) baseParts.pop();
    } else {
      baseParts.push(part);
    }
  }

  return baseParts.join('/');
}

export function computeDependencyGraph(files: FileContent[]) {
  const graph = new Map<string, Set<string>>();
  
  const pathToId = new Map<string, string>();
  for (const file of files) {
    pathToId.set(file.name, file.id);
    const noExt = file.name.replace(/\.(ts|tsx|js|jsx|mjs|cjs|css)$/, '');
    pathToId.set(noExt, file.id);
    if (noExt.endsWith('/index')) {
      pathToId.set(noExt.replace(/\/index$/, ''), file.id);
    }
  }

  for (const file of files) {
    const imports = new Set<string>();
    let match: RegExpExecArray | null;
    
    IMPORT_REGEX.lastIndex = 0;
    while ((match = IMPORT_REGEX.exec(file.content)) !== null) {
      const importPath = match[1] || match[2];
      if (!importPath) continue;
      if (!importPath.startsWith('.') && !importPath.startsWith('/')) continue;
      
      const importerDir = file.name.includes('/')
        ? file.name.substring(0, file.name.lastIndexOf('/'))
        : '';
      const resolved = resolvePath(importerDir, importPath);
      
      const targetId = pathToId.get(resolved);
      if (targetId && targetId !== file.id) {
        imports.add(targetId);
      }
    }
    
    if (imports.size > 0) {
      graph.set(file.id, imports);
    }
  }
  
  return graph;
}

export interface NodeDatum extends d3.SimulationNodeDatum {
  id: string;
  file: FileContent;
}

export interface LinkDatum extends d3.SimulationLinkDatum<NodeDatum> {
  sourceId: string;
  targetId: string;
}

export function buildAutoGraph(
  files: FileContent[],
  existingAutoShapes: CanvasShape[]
): { shapes: CanvasShape[]; arrows: CanvasArrow[] } {
  const depGraph = computeDependencyGraph(files);

  const nodes: NodeDatum[] = files.map(file => {
    // Determine position:
    // 1. Already laid out previously or dragged by user (existingAutoShapes)
    // 2. New node: center with slight jitter so D3-force can spread it
    const existing = existingAutoShapes.find(s => s.id === file.id);
    
    let x = existing?.x ?? (400 + (Math.random() - 0.5) * 50);
    let y = existing?.y ?? (300 + (Math.random() - 0.5) * 50);
    
    return {
      id: file.id,
      file,
      x,
      y,
      // Fix nodes that already exist so they don't move around!
      fx: existing ? existing.x : undefined,
      fy: existing ? existing.y : undefined
    };
  });

  const links: LinkDatum[] = [];
  depGraph.forEach((targets, sourceId) => {
    targets.forEach(targetId => {
      links.push({
        source: sourceId,
        target: targetId,
        sourceId,
        targetId
      });
    });
  });

  // Run a quick D3 simulation for new nodes to settle them
  // We use high alpha decay to make it settle quickly
  const simulation = d3.forceSimulation<NodeDatum, LinkDatum>(nodes)
    .force('link', d3.forceLink<NodeDatum, LinkDatum>(links).id(d => d.id).distance(150))
    .force('charge', d3.forceManyBody().strength(-500))
    .force('collide', d3.forceCollide().radius(70))
    .alphaDecay(0.05);
  
  // Run it synchronously until it cools
  for (let i = 0; i < 120; i++) {
    simulation.tick();
  }
  simulation.stop();

  // Convert back to CanvasShapes and Arrows
  const shapes: CanvasShape[] = nodes.map(n => ({
    id: n.id,
    type: 'rect',
    x: n.x ?? 0,
    y: n.y ?? 0,
    width: 140,
    height: 50,
    label: n.file.name.split('/').pop() || 'file',
    fill: '#1e293b', // Dark distinct background for files
    fileId: n.file.id,
    isAutoGenerated: true,
  }));

  const arrows: CanvasArrow[] = links.map(l => ({
    id: `auto-arrow-${l.sourceId}-${l.targetId}`,
    fromId: l.sourceId,
    toId: l.targetId,
    isAutoGenerated: true
  }));

  return { shapes, arrows };
}
